"""init

Revision ID: 05a57ad42fb5
Revises: 
Create Date: 2021-10-21 16:35:57.713990

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05a57ad42fb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_numbers')
    # ### end Alembic commands ###
